package org.zone.permissions;

@SuppressWarnings("unused")
public enum ZonePermissions implements ZonePermission {
    //meta region
    REGION_CREATE_BOUNDS_EXACT(false, "zone", "region", "create", "bounds", "exact"),
    REGION_CREATE_BOUNDS_CHUNK(false, "zone", "region", "create", "bounds", "chunk"),
    REGION_CREATE_SUB_BOUNDS_EXACT(true, "zone", "region", "create", "sub", "bounds", "exact"),
    REGION_CREATE_SUB_BOUNDS_CHUNK(true, "zone", "region", "create", "sub", "bounds", "chunk"),
    REGION_BASIC_INFO(true, "zone", "region", "info", "basic"),
    REGION_ADMIN_INFO(false, "zone", "region", "info", "admin"),
    REGION_EDIT_BOUNDS_EXACT(false, "zone", "region", "edit", "bounds", "exact"),
    REGION_EDIT_BOUNDS_CHUNK(false, "zone", "region", "edit", "bounds", "chunk"),
    REGION_LEAVE(true, "zone", "region", "leave"),
    REGION_INFO_SHOW_BOUNDS(true, "zone", "region", "info", "show"),

    //meta region override
    OVERRIDE_REGION_CREATE_BOUNDS_EXACT(false,
            "zone",
            "override",
            "region",
            "create",
            "bounds",
            "exact"),
    OVERRIDE_REGION_CREATE_BOUNDS_CHUNK(false,
            "zone",
            "override",
            "region",
            "create",
            "bounds",
            "chunk"),
    OVERRIDE_REGION_CREATE_SUB_BOUNDS_EXACT(false,
            "zone",
            "override",
            "region",
            "create",
            "sub",
            "bounds",
            "exact"),
    OVERRIDE_REGION_CREATE_SUB_BOUNDS_CHUNK(false,
            "zone",
            "override",
            "region",
            "create",
            "sub",
            "bounds",
            "chunk"),
    OVERRIDE_REGION_BASIC_INFO(false, "zone", "override", "region", "info", "basic"),
    OVERRIDE_REGION_ADMIN_INFO(false, "zone", "override", "region", "info", "admin"),
    OVERRIDE_REGION_EDIT_BOUNDS_EXACT(false,
            "zone",
            "override",
            "region",
            "edit",
            "bounds",
            "exact"),
    OVERRIDE_REGION_EDIT_BOUNDS_CHUNK(false,
            "zone",
            "override",
            "region",
            "edit",
            "bounds",
            "chunk"),
    OVERRIDE_REGION_INFO_SHOW_BOUNDS(false, "zone", "override", "region", "info", "show"),


    //place block
    FLAG_BLOCK_INTERACTION_PLACE_ENABLE(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "enable"),
    FLAG_BLOCK_INTERACTION_PLACE_VIEW(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "view"),
    FLAG_BLOCK_INTERACTION_PLACE_SET_GROUP(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "group"),

    //place block override
    OVERRIDE_FLAG_BLOCK_INTERACTION_PLACE_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "enable"),
    OVERRIDE_FLAG_BLOCK_INTERACTION_PLACE_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "view"),
    OVERRIDE_FLAG_BLOCK_INTERACTION_PLACE_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "place",
            "group"),

    //break block
    FLAG_BLOCK_INTERACTION_BREAK_ENABLE(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "enable"),
    FLAG_BLOCK_INTERACTION_BREAK_VIEW(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "view"),
    FLAG_BLOCK_INTERACTION_BREAK_SET_GROUP(true,
            "zone",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "group"),

    //break block override
    OVERRIDE_FLAG_BLOCK_INTERACTION_BREAK_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "enable"),
    OVERRIDE_FLAG_BLOCK_INTERACTION_BREAK_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "view"),
    OVERRIDE_FLAG_BLOCK_INTERACTION_BREAK_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "block",
            "interaction",
            "break",
            "group"),

    //door interaction
    FLAG_DOOR_INTERACTION_ENABLE(true, "zone", "region", "flag", "door", "interaction", "enable"),
    FLAG_DOOR_INTERACTION_VIEW(true, "zone", "region", "flag", "door", "interaction", "view"),
    FLAG_DOOR_INTERACTION_SET_GROUP(true,
            "zone",
            "region",
            "flag",
            "door",
            "interaction",
            "set",
            "group"),

    //door interaction override
    OVERRIDE_FLAG_DOOR_INTERACTION_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "door",
            "interaction",
            "enable"),
    OVERRIDE_FLAG_DOOR_INTERACTION_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "door",
            "interaction",
            "view"),
    OVERRIDE_FLAG_DOOR_INTERACTION_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "door",
            "interaction",
            "set",
            "group"),

    //itemframe interaction
    FLAG_ITEM_FRAME_INTERACTION_ENABLE(true,
            "zone",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "enable"),
    FLAG_ITEM_FRAME_INTERACTION_VIEW(true,
            "zone",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "view"),
    FLAG_ITEM_FRAME_INTERACTION_SET_GROUP(true,
            "zone",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "group"),

    //itemframe interaction override
    OVERRIDE_FLAG_ITEM_FRAME_INTERACTION_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "enable"),
    OVERRIDE_FLAG_ITEM_FRAME_INTERACTION_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "view"),
    OVERRIDE_FLAG_ITEM_FRAME_INTERACTION_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "itemframe",
            "interaction",
            "break",
            "group"),

    //member
    FLAG_MEMBER_CHANGE(true, "zone", "region", "flag", "member", "group", "change"),
    FLAG_MEMBERS_VIEW(true, "zone", "region", "flag", "member", "group", "view"),

    //member override
    OVERRIDE_FLAG_MEMBER_CHANGE(false,
            "zone",
            "override",
            "region",
            "flag",
            "member",
            "group",
            "change"),
    OVERRIDE_FLAG_MEMBERS_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "member",
            "group",
            "view"),


    //greetings
    FLAG_GREETINGS_SET(true, "zone", "region", "flag", "greetings", "set", "message"),
    FLAG_GREETINGS_VIEW(true, "zone", "region", "flag", "greetings", "view"),
    FLAG_GREETINGS_REMOVE(true, "zone", "region", "flag", "greetings", "remove"),

    //greetings override
    OVERRIDE_FLAG_GREETINGS_SET(false,
            "zone",
            "override",
            "region",
            "flag",
            "greetings",
            "set",
            "message"),
    OVERRIDE_FLAG_GREETINGS_VIEW(false, "zone", "override", "region", "flag", "greetings", "view"),
    OVERRIDE_FLAG_GREETINGS_REMOVE(false,
            "zone",
            "override",
            "region",
            "flag",
            "greetings",
            "remove"),

    //leavings
    FLAG_LEAVING_SET(true, "zone", "region", "flag", "leaving", "set", "message"),
    FLAG_LEAVING_VIEW(true, "zone", "region", "flag", "leaving", "view"),
    FLAG_LEAVING_REMOVE(true, "zone", "region", "flag", "leaving", "remove"),

    //leavings override
    OVERRIDE_FLAG_LEAVING_SET(false,
            "zone",
            "override",
            "region",
            "flag",
            "leaving",
            "set",
            "message"),
    OVERRIDE_FLAG_LEAVING_VIEW(false, "zone", "override", "region", "flag", "leaving", "view"),
    OVERRIDE_FLAG_LEAVING_REMOVE(false, "zone", "override", "region", "flag", "leaving", "remove"),

    //entry player
    FLAG_ENTRY_PLAYER_SET_GROUP(true, "zone", "region", "flag", "entry", "player", "set", "group"),
    FLAG_ENTRY_PLAYER_VIEW(true, "zone", "region", "flag", "entry", "player", "view"),
    FLAG_ENTRY_PLAYER_ENABLE(true, "zone", "region", "flag", "entry", "player", "enable"),

    //entry player override
    OVERRIDE_FLAG_ENTRY_PLAYER_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "entry",
            "player",
            "set",
            "group"),
    OVERRIDE_FLAG_ENTRY_PLAYER_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "entry",
            "player",
            "view"),
    OVERRIDE_FLAG_ENTRY_PLAYER_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "entry",
            "player",
            "enable"),

    //entry monster
    FLAG_ENTRY_MONSTER_VIEW(true, "zone", "region", "flag", "entry", "monster", "view"),
    FLAG_ENTRY_MONSTER_ENABLE(true, "zone", "region", "flag", "entry", "monster", "enable"),

    //entry monster override
    OVERRIDE_FLAG_ENTRY_MONSTER_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "entry",
            "monster",
            "view"),
    OVERRIDE_FLAG_ENTRY_MONSTER_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "entry",
            "monster",
            "enable"),

    //damage attack
    FLAG_DAMAGE_ATTACK_SET_GROUP(true,
            "zone",
            "region",
            "flag",
            "damage",
            "attack",
            "set",
            "group"),
    FLAG_DAMAGE_ATTACK_VIEW(true, "zone", "region", "flag", "damage", "attack", "view"),
    FLAG_DAMAGE_ATTACK_ENABLE(true, "zone", "region", "flag", "damage", "attack", "enable"),

    //damage attack override
    OVERRIDE_FLAG_DAMAGE_ATTACK_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "attack",
            "set",
            "group"),
    OVERRIDE_FLAG_DAMAGE_ATTACK_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "attack",
            "view"),
    OVERRIDE_FLAG_DAMAGE_ATTACK_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "attack",
            "enable"),

    //damage fall
    FLAG_DAMAGE_FALL_SET_GROUP(true, "zone", "region", "flag", "damage", "fall", "set", "group"),
    FLAG_DAMAGE_FALL_VIEW(true, "zone", "region", "flag", "damage", "fall", "view"),
    FLAG_DAMAGE_FALL_ENABLE(true, "zone", "region", "flag", "damage", "fall", "enable"),

    //damage fall override
    OVERRIDE_FLAG_DAMAGE_FALL_SET_GROUP(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "fall",
            "set",
            "group"),
    OVERRIDE_FLAG_DAMAGE_FALL_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "fall",
            "view"),
    OVERRIDE_FLAG_DAMAGE_FALL_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "damage",
            "fall",
            "enable"),

    //tnt defuse
    FLAG_TNT_DEFUSE_ENABLE(false, "zone", "region", "flag", "tnt", "defuse", "enable"),
    FLAG_TNT_DEFUSE_VIEW(false, "zone", "region", "flag", "tnt", "defuse", "view"),

    //tnt defuse override
    OVERRIDE_FLAG_TNT_DEFUSE_ENABLE(false,
            "zone",
            "override",
            "region",
            "flag",
            "tnt",
            "defuse",
            "enable"),
    OVERRIDE_FLAG_TNT_DEFUSE_VIEW(false,
            "zone",
            "override",
            "region",
            "flag",
            "tnt",
            "defuse",
            "view"),

    //balance
    FLAG_BALANCE_VIEW(true, "zone", "region", "flag", "balance", "view"),

    //balance override
    OVERRIDE_FLAG_BALANCE_VIEW(false, "zone", "override", "region", "flag", "balance", "view"),

    //bypasses
    BYPASS_DOOR_INTERACTION(false, "zone", "bypass", "interaction", "door"),
    BYPASS_BLOCK_INTERACTION_PLACE(false, "zone", "bypass", "interaction", "block", "place"),
    BYPASS_BLOCK_INTERACTION_BREAK(false, "zone", "bypass", "interaction", "block", "break"),
    BYPASS_ITEM_FRAME_INTERACTION(false, "zone", "bypass", "interaction", "itemframe"),
    BYPASS_DAMAGE_FALL(false, "zone", "bypass", "damage", "fall"),
    BYPASS_DAMAGE_ATTACK(false, "zone", "bypass", "damage", "attack"),
    BYPASS_ENTRY(false, "zone", "bypass", "entry");

    private final String[] nodes;
    private final boolean isDefault;

    ZonePermissions(boolean isDefault, String... nodes) {
        this.isDefault = isDefault;
        this.nodes = nodes;
    }

    @Override
    public String[] getPermissionNode() {
        return this.nodes;
    }

    @Override
    public boolean isDefaultAllowed() {
        return this.isDefault;
    }
}
